apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-ext-pdf-deployment
  namespace: default
  labels:
    app: ia-ext-pdf
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0 # number of pods that can be created above the desired amount
      maxUnavailable: 1 # number of pods that can be unavailable during the update
  replicas: 1
  revisionHistoryLimit: 2 # number of old replica sets to keep
  selector:
    matchLabels:
      app: ia-ext-pdf
  template:
    metadata:
      labels:
        app: ia-ext-pdf
    spec:
      topologySpreadConstraints:  # deploy pods as evenly distributed as possible
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: ia-ext-pdf
      containers:
        - name: ia-ext-pdf
          image: 10.151.0.4/nssycnat/ia_extraccion_pdf:0f46bf5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
              cpu: 0.2
              ephemeral-storage: 512Mi
            limits:
              memory: 2Gi
              cpu: 1
              ephemeral-storage: 1Gi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10 # Delay before start probe
            timeoutSeconds: 1 # seconds after the probes times up
            failureThreshold: 1 # how many tries before consider pod not ready
            periodSeconds: 10 # how often to perform the probe
          livenessProbe:
            exec:
              command: # run a command to check if process is up
                - /bin/sh
                - -c
                - "pidof -x uvicorn"
            initialDelaySeconds: 10
            failureThreshold: 2
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: ia-ext-pdf
spec:
  type: LoadBalancer
  loadBalancerIP: 10.151.0.32
  selector:
    app: ia-ext-pdf
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 8080 # pod port
